### ISSUE TITLE
Matrix Set element bug

### ISSUE THREAD

**Issue by wmcnicho** [wmcnicho/QCP_SP2015#16]
Matrix blows up on sparse representation "Out of bounds exception"

Side note, you can close issues from a commit by adding "Close #x" in your commit message and it will link it to the commit with the fix.

**Comment by gennarodp** [comment]
"sparse" calls the general sparse matrix class which isn't used to i don't know if it's worth hunting down the errors in it.
At the moment we have "gate" which is an optimized version of the sparse matrix class specifically for gates which works. So i think it's probably worth just removing the general sparse class.
