### ISSUE TITLE
Problems with git

### ISSUE THREAD

**Issue by cm66** [wmcnicho/QCP_SP2015#6]
Hey everyone!

I'd like to upload my latest version of the Sparsematrix-Class, but git won't let me...
when I "pull", there's a file-conflict and when i "push" or do anything else, it rejects everything saying "first pull"

What shall I do?

**Comment by cm66** [comment]
Hey! I put 2 files on Dropbox, probably somebody has time and skills to upload it to our project?
Thanks!

**Comment by wmcnicho** [comment]
For future reference I believe that the issue you were having was that you pulled before pushing (as you should) but there were new files on the remote repository. To fix this simply commit your code again unless there are conflicts (then fix them first and then commit).
